before:
  hooks:
    - go mod tidy
builds:
  - main: ./folder/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
archives:
  - replacements:
      darwin: Darwin
brews:
- name: testingmacsko
  homepage: https://github.com/macsko/homebrew-taps
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
  custom_require: "../private_strategy"
  folder: formula
  tap:
    owner: macsko
    name: homebrew-taps
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
