builds:
  - main: ./proton/folder/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
archives:
  - replacements:
      darwin: macOS
checksum:
  disable: true
brews:
- name: proton
  homepage: "https://github.com/Bidroombv/protorepo"
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
  custom_require: "../private_strategy"
  folder: formula
  tap:
    owner: macsko
    name: homebrew-taps
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
