# before:
#   hooks:
#     - go mod tidy
builds:
  - main: ./src/cmd/proton/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: macOS
checksum:
  disable: true
brews:
- name: proton
  homepage: "https://github.com/Bidroombv/protorepo"
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
  custom_require: "../private_strategy"
  folder: formula
  tap:
    owner: Bidroombv
    name: homebrew-tap
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
