name: Quality control pull requests - protobuf
on: 
  pull_request:
    paths:
      - '**.proto'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: 0.36.0
      - run: buf lint

  proton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: echo "OK"

  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "true"
