name: linter

on:
  pull_request

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "."
        pylint-options: "--rcfile=.pylintrc"
        