name: linter

on:
  pull_request

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "."
          use-pylint: true
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: "--rcfile=.pylintrc"
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
        